### ISSUE TITLE
ENH: Add generation functions

### ISSUE THREAD

**Issue by zhongnanxu** [uw-cmg/StructOpt_modular#11]
I was looking at the generation functions, and I'm going to rework it a little. Right now, there is no obvious way to implement other generation functions outside of adding to the generate in the common/generators/**init**.py  I was thinking about making this a class and do class inheritance, but I thought it'd be better to just change the code on the individual level and have it dynamically call different generate functions. 

I will work on this and tell you when I am done.

**Comment by jjmaldonis** [comment]
@zhongnanxu should we close this? I think it was finished in PR #35

**Comment by zhongnanxu** [comment]
Sure.
