### ISSUE TITLE
TXF: Submitting Mutations

### ISSUE THREAD

**Issue by cmgtam** [uw-cmg/StructOpt_modular#25]
Transferred issue from uw-cmg/MAST. Close if it no longer applies.

In the current interface set up, energy evaluations only occur once per generation after all of the crossovers and mutations have been performed. This means that, if users are submitting their individuals to queue for energy evaluations, any mutations that involve energy evaluations cannot be performed using the MAST-StructOpt interface. This means that users will not be able to take full advantage of mutations such as quenching or basin hopping. To fix this, programmers would need to either retain some memory of the mutations performed on the structures to alter the LAMMPS/VASP input accordingly or they would need to develop a method for submitting mutations to the queue.

**Comment by jjmaldonis** [comment]
NTS: The basin hopping mutation does a series of random atom moves / lattice mutations and runs the cost function for each of those moves, using a MC scheme to accept/reject each move.

Currently this structopt does not support basin hopping or quenching, and if/when it does, we will write a new `optimizer.py`-like file for it. Writing a new optimizer removes the need for running the cost function within any mutations, so this will not be a problem. Basin hopping (and quenching?) are not planned to be allowed mutations within the genetic algorithm scheme under this framework; if someone wants that, we need to think carefully about how to implement it without breaking the architecture and flow of the package.
